services:

    db:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_DB: lireddit
  
    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - 8080:8080
  